# AppVeyor build configuration for JavaScript project
version: 1.0.{build}

image: Visual Studio 2017
environment:
  nodejs_version: "Stable"
  PYTHON: "C:\\Python36-x64"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk9"
platform: Any CPU
configuration: Release

init:
- tzutil /s "UTC"

# Install Node 8
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%JAVA_HOME%\bin;%PATH%

# Projects
clone_depth: 1
branches:
  only:
  - master
  - /[Ff]eature\/.+/
  - /[Ff]ix\/.+/
  - /[Hh]otfix\/.+/

build:
  parallel: true

build_script:
- cmd: >-
    CALL wmic os get caption, version, osarchitecture

    CALL node -v

    CALL npm -v

    CALL node -e "console.log(process.versions.v8);"

    cd .NET\

    cd ..\JavaScript\
    
    cd ..\Python\
    
    build.cmd

    cd ..\java\
    

# disable automatic tests
test:
          
test_script:
    - cd ..\Python\
    - ECHO.
    - ECHO # Installing recognizers-text
    - CALL  pip install -e .\libraries\recognizers-text\

    - ECHO.
    - ECHO # Installing recognizers-number
    - CALL  pip install -e .\libraries\recognizers-number\

    - ECHO.
    - ECHO # Installing recognizers-number-with-unit
    - CALL  pip install -e .\libraries\recognizers-number-with-unit\

    - ECHO.
    - ECHO # Installing recognizers-date-time
    - CALL  pip install -e .\libraries\recognizers-date-time\

    - ECHO.
    - ECHO # Installing recognizers-sequence
    - CALL  pip install -e .\libraries\recognizers-sequence\

    - ECHO.
    - ECHO # Installing recognizers-suite
    - CALL  pip install -e .\libraries\recognizers-suite\

    - ECHO.
    - ECHO # Installing Test Dependencies
    - CALL pip install -r .\tests\requirements.txt

    - ECHO.
    - ECHO # Running tests
    - CALL pytest --tb=line

artifacts:
    - path: '**\*Microsoft.Recognizers*.nupkg'
      name: NuGets
    - path: 'Java\libraries\**\recognizers-text*.jar'
      name: JARs
